from typing import Protocol
from .entities import Fault

class AlertRepository(Protocol):
    def save(self, fault: Fault) -> None: ...
    def remove(self, fault: Fault) -> None: ...

class Handle(Protocol):
    @classmethod
    def create_message(cls, fault: Fault)-> tuple[str, str]: ...

class Sender(Protocol):
    @staticmethod
    def send_message(chat_id, text) -> None: ...

    def send_fault(self, fault: Fault) -> None: ...

def get_chat_id(name): ...